# Generated by Django 4.1.7 on 2023-04-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
